FROM node:18-alpine AS base

FROM base AS shared
WORKDIR /app/shared
COPY ./shared/package*.json .
RUN npm install

FROM base AS server
WORKDIR /app/server
COPY ./server/package*.json .
RUN npm install

FROM base AS main
WORKDIR /app/server
# Install curl for health checks
RUN apk update && apk add curl
COPY --from=shared /app/shared /app/shared
COPY --from=server /app/server /app/server

CMD npm run dev
